
const LOCAL_STORAGE_KEY = "product.cart"
const LOCAL_STORAGE_KEY_EGGS = "eggs"
const LOCAL_STORAGE_KEY_FISHS = "fishs"
const LOCAL_STORAGE_KEY_RICES = "rices"
const LOCAL_STORAGE_KEY_EGGSINS = "eggs.ins"
const LOCAL_STORAGE_KEY_FISHSINS = "fishs.ins"
const LOCAL_STORAGE_KEY_RICESINS = "rices.ins"




exports  = {
      LOCAL_STORAGE_KEY: LOCAL_STORAGE_KEY,
    LOCAL_STORAGE_KEY_EGGS:LOCAL_STORAGE_KEY_EGGS,
    LOCAL_STORAGE_KEY_FISHS:LOCAL_STORAGE_KEY_FISHS,
    LOCAL_STORAGE_KEY_RICES:LOCAL_STORAGE_KEY_RICES,
    LOCAL_STORAGE_KEY_EGGSINS:LOCAL_STORAGE_KEY_EGGSINS,
    LOCAL_STORAGE_KEY_FISHSINS:LOCAL_STORAGE_KEY_FISHSINS,
    LOCAL_STORAGE_KEY_RICESINS:LOCAL_STORAGE_KEY_RICESINS,

      
  }